fixtures:
  repositories:
    archive: "https://github.com/voxpupuli/puppet-archive"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib"
    systemd: "https://github.com/camptocamp/puppet-systemd"
    file_capability: "https://github.com/smoeding/puppet-file_capability"
